// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4BAyxOXeoQN23CBfEkTggMoknSw9db0I',
    appId: '1:230192212218:web:986d318240122c37a38143',
    messagingSenderId: '230192212218',
    projectId: 'siap-apps',
    authDomain: 'siap-apps.firebaseapp.com',
    storageBucket: 'siap-apps.appspot.com',
    measurementId: 'G-BPX9E845T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkf45q0rLV4mx3_GFipHyR3T3W1UQJIwI',
    appId: '1:230192212218:android:5e8a3426f797212ea38143',
    messagingSenderId: '230192212218',
    projectId: 'siap-apps',
    storageBucket: 'siap-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxJm1mTUoSr9E81HZ1ldPIWhTEONc0bY4',
    appId: '1:230192212218:ios:b4f44a22453f64b3a38143',
    messagingSenderId: '230192212218',
    projectId: 'siap-apps',
    storageBucket: 'siap-apps.appspot.com',
    iosBundleId: 'com.example.siapAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxJm1mTUoSr9E81HZ1ldPIWhTEONc0bY4',
    appId: '1:230192212218:ios:88f1a810ba8c201ca38143',
    messagingSenderId: '230192212218',
    projectId: 'siap-apps',
    storageBucket: 'siap-apps.appspot.com',
    iosBundleId: 'com.example.siapAppNew.RunnerTests',
  );
}
